---
- name: Update the repository cache
  apt:
    update_cache: true
  become: true

- name: Set hostname
  hostname:
    name: "comicwiki.dk"
  become: true

- name: Copy over hosts file
  template:
    src: hosts
    dest: /etc/hosts
    mode: 0644
    group: root
    owner: root
  become: true
  notify:
    - restart networking

- name: Install base packages
  apt: name={{ item }} state=present
  with_items:
    - ca-certificates
    - git
    - python
    - openssl
    - zip
    - imagemagick
    - openssh-server
    - rsync
    - ntpdate
  become: true

- name: Set timezone to Europe/Copenhagen
  timezone:
    name: Europe/Copenhagen
  become: true

- name: Create ntpdate cronjob
  copy:
    src: ntpdate.sh
    dest: /etc/cron.hourly/ntpdate.sh
    mode: 0755
    owner: root
    group: root
  become: true

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  become: true

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true

- name: Create local users
  user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: users,sudo,wheel
    append: true
  with_items:
    - joen
    - mads
  become: true

- name: Add authorized keys for Mads
  authorized_key:
    user: mads
    key: "{{ lookup('file', 'files/mads.key.pub') }}"

- name: Add authorized keys for Joen
  authorized_key:
    user: joen
    key: "{{ lookup('file', 'files/joen.key.pub') }}"
  become: true
  become_user: joen
