---
- name: Update the repository cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Set hostname
  ansible.builtin.hostname:
    name: "comicwiki.dk"
  become: true
  when: not run_in_container

- name: Install base packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - ca-certificates
      - git
      - curl
      - python-is-python3
      - openssl
      - zip
      - gpg
      - imagemagick
      - openssh-server
      - rsync
      - ntpdate
      - tzdata
      - cron
      - util-linux-extra
  become: true

- name: Set timezone to Europe/Copenhagen
  community.general.timezone:
    name: Europe/Copenhagen
  become: true

- name: Create ntpdate cronjob
  ansible.builtin.copy:
    src: ntpdate.sh
    dest: /etc/cron.hourly/ntpdate.sh
    mode: 0755
    owner: root
    group: root
  become: true

- name: Make sure we have a 'wheel' group
  ansible.builtin.group:
    name: wheel
    state: present
  become: true

- name: Allow 'wheel' group to have passwordless sudo
  ansible.builtin.lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  become: true

- name: Create local users
  ansible.builtin.user:
    name: "{{ item }}"
    shell: /bin/bash
    groups: users,sudo,wheel
    append: true
  with_items:
    - joen
    - mads
  become: true

- name: Add authorized keys for Mads
  ansible.posix.authorized_key:
    user: mads
    key: "{{ lookup('file', 'files/mads.key.pub') }}"

- name: Add authorized keys for Joen
  ansible.posix.authorized_key:
    user: joen
    key: "{{ lookup('file', 'files/joen.key.pub') }}"
  become: true
  become_user: joen

- name: Set the domain name in the kernel
  ansible.posix.sysctl:
    name: kernel.domainname
    value: comicwiki.dk
    sysctl_file: /etc/sysctl.conf
    reload: true
  become: true
