---
- name: Install base packages
  apt: name={{ item }} state=present
  with_items:
    - ca-certificates
    - git
    - python
    - openssl
    - zip
    - imagemagick
    - openssh-server
    - rsync

- name: Create user for mads
  user:
    name: mads
    shell: /bin/bash
    groups: users,sudo
    append: true

- name: Add authorized keys
  authorized_key:
    user: mads
    key: "{{ lookup('file', 'files/mads.key.pub') }}"
