---
- name: Install certbot
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - certbot
      - python3-certbot-apache

- name: Make cli.ini file
  ansible.builtin.copy:
    src: cli.ini
    dest: /etc/letsencrypt/cli.ini
    mode: 0644
    group: root
    owner: root

- name: Make directories for hooks
  ansible.builtin.file:
    path: "/etc/letsencrypt/renewal-hooks/{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: true
  with_items:
    - pre
    - post
    - deploy

- name: Make directories for hooks
  ansible.builtin.file:
    path: "/etc/letsencrypt/renewal/"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Make renewal hooks
  ansible.builtin.copy:
    src: apache.sh
    dest: /etc/letsencrypt/renewal-hooks/
    mode: 0755
    owner: root
    group: root

- name: Make renewal job
  ansible.builtin.copy:
    src: cert-renew.sh
    dest: /etc/cron.daily/cert-renew.sh
    owner: root
    group: root
    mode: 0755

- name: Get www certificate
  ansible.builtin.command: certbot certonly --standalone --agree-tos --register-unsafely-without-email -d www.comicwiki.dk -d comicwiki.dk
  args:
    creates: /etc/letsencrypt/live/www.comicwiki.dk
  when: inventory_hostname != 'localhost'
  ignore_errors: true
