---
- name: Install certbot
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - certbot
      - python-certbot-apache

- name: Make cli.ini file
  copy:
    src: cli.ini
    dest: /etc/letsencrypt/cli.ini
    mode: 0644
    group: root
    owner: root

- name: Make directories for hooks
  file:
    path: "/etc/letsencrypt/renewal-hooks/{{ item }}"
    state: directory
    mode: 0755
    owner: root
    group: root
    recurse: true
  with_items:
    - pre
    - post
    - deploy

- name: Make directories for hooks
  file:
    path: "/etc/letsencrypt/renewal/"
    state: directory
    mode: 0755
    owner: root
    group: root

- name: Make renewal hooks
  copy:
    src: apache.sh
    dest: /etc/letsencrypt/renewal-hooks/
    mode: 0755
    owner: root
    group: root

- name: Make renewal job
  copy:
    src: cert-renew.sh
    dest: /etc/cron.daily/cert-renew.sh
    owner: root
    group: root
    mode: 0755

- name:
  debug:
    msg: ansible_facts.ansible_hostname

- name: Get www certificate
  command: certbot certonly --standalone --agree-tos --register-unsafely-without-email -d www.comicwiki.dk -d comicwiki.dk
  args:
    creates: /etc/letsencrypt/live/www.comicwiki.dk
  when: ansible_facts.ansible_hostname != 'localhost'
  ignore_errors: true

- name: Adjust renewal interval for certificate
  lineinfile:
    path: /etc/letsencrypt/renewal/www.comicwiki.dk.conf
    regexp: '^renew_before_expiry'
    line: 'renew_before_expiry = 7 days'
