---
- name: Save iptables
  ansible.builtin.command: |
    iptables-save > /etc/iptables/rules.v4 &&
    ip6tables-save > /etc/iptables/rules.v6

- name: Restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted

- name: Restart ssh
  ansible.builtin.service:
    name: sshd
    state: restarted
