---
- name: netfilter restart
  command: netfilter-persistent restart
  become: true

- name: unattended-upgrades restart
  service: name=unattended-upgrades state=restarted

- name: restart ssh
  service: name=sshd state=restarted
