---
- name: iptables save
  command: |
    iptables-save > /etc/iptables/rules.v4 &&
    ip6tables-save > /etc/iptables/rules.v6

- name: unattended-upgrades restart
  service:
    name: unattended-upgrades
    state: restarted

- name: restart ssh
  service:
    name: sshd
    state: restarted
