---
- name: Save iptables
  community.general.iptables_state:
    ip_version: "ip{{ item }}"
    table: filter
    state: saved
    path: "/etc/iptables/rules.{{ item }}"
  with_items:
    - v4
    - v6

- name: Restart unattended-upgrades
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted
  register: service
  failed_when: service is failed

- name: Restart ssh
  ansible.builtin.service:
    name: sshd
    state: restarted
  register: service
  failed_when: service is failed
