---
- name: iptables save
  ansible.builtin.command: |
    iptables-save > /etc/iptables/rules.v4 &&
    ip6tables-save > /etc/iptables/rules.v6

- name: unattended-upgrades restart
  ansible.builtin.service:
    name: unattended-upgrades
    state: restarted

- name: restart ssh
  ansible.builtin.service:
    name: sshd
    state: restarted
