services:
  web:
    image: mediawiki:1.39
    build:
      context: docker
    ports:
      - 9999:80
    links:
      - database
    depends_on:
      - database
    restart: unless-stopped
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
      - ./logo.png:/var/www/html/resources/assets/logo.png:ro
      - ./comicwiki:/var/www/html/resources/comicwiki:ro
  database:
    image: mariadb:10
    environment:
      MARIADB_DATABASE: 'comicwiki'
      MARIADB_USER: 'comicwiki'
      MARIADB_PASSWORD: 'password'
      MARIADB_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - database:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/:ro
    restart: unless-stopped
volumes:
  database:
