---
- name: download composer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/installer
  tags: composer

- name: Install composer
  shell: cat /tmp/installer | php -- --install-dir=/usr/local/bin
  args:
    creates: /usr/local/bin/composer
  tags: composer

- name: Rename composer.phar to composer
  synchronize:
    src: /usr/local/bin/composer.phar
    dest: /usr/local/bin/composer
    archive: true
  delegate_to: "{{ inventory_hostname }}"
  tags: composer

- name: Make composer executable
  file:
    path: /usr/local/bin/composer
    mode: a+x
    state: file
  tags: composer
