---
- name: Validate Composer checksum
  ansible.builtin.get_url:
    checksum: "sha384:dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6"
    dest: /usr/src/
    url: https://getcomposer.org/installer
  become: true

- name: Download and install Composer
  ansible.builtin.shell: curl -sS https://getcomposer.org/installer | php
  args:
    chdir: /usr/src/
    creates: /usr/local/bin/composer-setup.php
  become: true

- name: List directory /usr/src/
  ansible.builtin.find:
    paths: /usr/src/
    hidden: true

- name: Add Composer to global path
  ansible.builtin.copy:
    dest: /usr/local/bin/composer
    src: /usr/src/composer.phar
    group: root
    mode: "0755"
    owner: root
    remote_src: true
  become: true
