---
- name: Install PHP and mysql
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - php
      - php-mysqli
      - php-mbstring
      - php-json
      - php-common
      - php-xml
      - php-curl
      - php-intl
  become: true

- name: Delete /var/www/html/index.html file
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent
  become: true

- name: Check
  ansible.builtin.stat:
    path: /var/www/html/.git
  register: installation

- name: Install Mediawiki
  ansible.builtin.git:
    repo: https://github.com/wikimedia/mediawiki.git
    dest: /var/www/html/
    version: REL1_39
    depth: 1
    update: false
  become: true
  when: not installation.stat.exists

- name: Set Mediawiki owner/group rights correctly
  ansible.builtin.file:
    path: /var/www/
    state: directory
    recurse: true
    owner: www-data
    group: www-data
  become: true

- name: Install Composer
  ansible.builtin.include_tasks: composer.yml

- name: Copy over composer.local.json
  ansible.builtin.copy:
    src: "composer.local.json"
    dest: "/var/www/html/composer.local.json"
    mode: 0644
    owner: www-data
    group: www-data
  become: true
  become_user: root

- name: Install dependencies via composer
  community.general.composer:
    command: update
    arguments: "--no-install --no-progress"
    working_dir: "/var/www/html"
    no_dev: true
  become: true
  become_user: www-data

- name: Create skin resources
  ansible.builtin.file:
    path: "/var/www/html/resources/comicwiki/images"
    state: directory
    mode: "0755"
    owner: "www-data"
    group: "www-data"
    recurse: true
  become: true

- name: Copy necessary resources
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: www-data
    group: www-data
  with_items:
    - {src: "comicwiki.scss", dest: "/var/www/html/resources/comicwiki/comicwiki.scss"}
    - {src: "comicwiki-header.xml", dest: "/var/www/html/resources/comicwiki/comicwiki-header.xml"}
    - {src: "comicwiki.css.map", dest: "/var/www/html/resources/comicwiki/comicwiki.css.map"}
    - {src: "comicwiki.js", dest: "/var/www/html/resources/comicwiki/comicwiki.js"}
  become: true
  # notify:
  #   - Reset chameleon

- name: Copy over the local settings file
  ansible.builtin.template:
    src: LocalSettings.php.j2
    dest: /var/www/html/LocalSettings.php
    mode: 0400
    owner: www-data
    group: www-data
  become: true

- name: Ignore comicwiki resources dir
  ansible.builtin.lineinfile:
    path: /var/www/html/.git/info/exclude
    line: 'resources/comicwiki/'
    state: present
  become: true

- name: Make favicon
  ansible.builtin.copy:
    src: favicon.ico
    dest: /var/www/html/favicon.ico
    mode: 0644
    group: www-data
    owner: www-data
  become: true

- name: Copy over robots.txt
  ansible.builtin.copy:
    src: robots.txt
    dest: /var/www/html/robots.txt
    mode: 0644
    group: www-data
    owner: www-data
  become: true

- name: Create images
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    group: www-data
    owner: www-data
  with_items:
    - {src: "images/btn_oversigt_inner.png", dest: "/var/www/html/resources/comicwiki/images/btn_oversigt_inner.png"}
    - {src: "images/btn_oversigt.png", dest: "/var/www/html/resources/comicwiki/images/btn_oversigt.png"}
    - {src: "images/discussionitem_icon.gif", dest: "/var/www/html/resources/comicwiki/images/discussionitem_icon.gif"}
    - {src: "images/icon_cleanup.gif", dest: "/var/www/html/resources/comicwiki/images/icon_cleanup.gif"}
    - {src: "images/icon_disambiguation.gif", dest: "/var/www/html/resources/comicwiki/images/icon_disambiguation.gif"}
    - {src: "images/icon_disambiguation_micro.gif", dest: "/var/www/html/resources/comicwiki/images/icon_disambiguation_micro.gif"}
    - {src: "images/icon_disputed.gif", dest: "/var/www/html/resources/comicwiki/images/icon_disputed.gif"}
    - {src: "images/icon_info.gif", dest: "/var/www/html/resources/comicwiki/images/icon_info.gif"}
    - {src: "images/icon_merge.gif", dest: "/var/www/html/resources/comicwiki/images/icon_merge.gif"}
    - {src: "images/icon_stub.gif", dest: "/var/www/html/resources/comicwiki/images/icon_stub.gif"}
    - {src: "images/Icon_inducks.gif", dest: "/var/www/html/resources/comicwiki/images/Icon_inducks.gif"}
    - {src: "images/Icon_Nummer_9_MM.gif", dest: "/var/www/html/resources/comicwiki/images/Icon_Nummer_9_MM.gif"}
    - {src: "images/Icon_Planet_Pulp.gif", dest: "/var/www/html/resources/comicwiki/images/Icon_Planet_Pulp.gif"}
    - {src: "images/Icon_ddfr.gif", dest: "/var/www/html/resources/comicwiki/images/Icon_ddfr.gif"}
    - {src: "images/logo.png", dest: "/var/www/html/resources/assets/logo.png"}
  become: true
