---
- name: Install PHP and mysql
  apt: name={{ item }} state=present
  with_items:
    - php7.2
    - php7.2-mysqli
    - php7.2-mbstring
    - php7.2-json
    - php7.2-common
    - php7.2-xml
  become: true

- name: Delete /var/www/html/index.html file
  file:
    path: /var/www/html/index.html
    state: absent
  become: true

- name: Install Mediawiki
  git:
    repo: https://gerrit.wikimedia.org/r/p/mediawiki/core.git
    dest: /var/www/html/
    version: REL1_31
    depth: 1
    update: false
  become: true
  become_user: www-data
  tags: never

- include_tasks: composer.yml

- name: Install dependencies via composer
  composer:
    command: install
    working_dir: /var/www/html
    no_dev: true
  become: true
  become_user: www-data

- name: Copy necessary resources
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    owner: www-data
    group: www-data
  with_items:
    - {src: "comicwiki.less", dest: "/var/www/html/resources/comicwiki/comicwiki.less"}
    - {src: "comicwiki-header.xml", dest: "/var/www/html/resources/comicwiki/comicwiki-header.xml"}
    - {src: "comicwiki.css.map", dest: "/var/www/html/resources/comicwiki/comicwiki.css.map"}
    - {src: "comicwiki.js", dest: "/var/www/html/resources/comicwiki/comicwiki.js"}
    - {src: "logo.png", dest: "/var/www/html/resources/assets/logo.png"}
  become: true
  notify:
    - reset chameleon

- name: Copy over the local settings file
  template:
    src: LocalSettings.php.j2
    dest: /var/www/html/LocalSettings.php
    mode: 0600
    owner: www-data
    group: www-data
  become: true

- name: Create resources directory for comicwiki.dk
  file:
    path: /var/www/html/resources/comicwiki/images
    state: directory
    mode: 0755
    owner: www-data
    group: www-data
    recurse: true
  become: true

- name: Ignore comicwiki resources dir
  lineinfile:
    path: /var/www/html/.git/info/exclude
    line: 'resources/comicwiki/'
    state: present
  become: true

- name: Make favicon
  copy:
    src: favicon.ico
    dest: /var/www/html/favicon.ico
    mode: 0644
    group: www-data
    owner: www-data
  become: true

- name: Create images
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
    group: www-data
    owner: www-data
  with_items:
    - {src: "images/btn_oversigt_inner.png", dest: "/var/www/html/resources/comicwiki/images/btn_oversigt_inner.png"}
    - {src: "images/btn_oversigt.png", dest: "/var/www/html/resources/comicwiki/images/btn_oversigt.png"}
    - {src: "images/discussionitem_icon.gif", dest: "/var/www/html/resources/comicwiki/images/discussionitem_icon.gif"}
    - {src: "images/icon_cleanup.gif", dest: "/var/www/html/resources/comicwiki/images/icon_cleanup.gif"}
    - {src: "images/icon_disambiguation.gif", dest: "/var/www/html/resources/comicwiki/images/icon_disambiguation.gif"}
    - {src: "images/icon_disambiguation_micro.gif", dest: "/var/www/html/resources/comicwiki/images/icon_disambiguation_micro.gif"}
    - {src: "images/icon_disputed.gif", dest: "/var/www/html/resources/comicwiki/images/icon_disputed.gif"}
    - {src: "images/icon_info.gif", dest: "/var/www/html/resources/comicwiki/images/icon_info.gif"}
    - {src: "images/icon_merge.gif", dest: "/var/www/html/resources/comicwiki/images/icon_merge.gif"}
    - {src: "images/icon_stub.gif", dest: "/var/www/html/resources/comicwiki/images/icon_stub.gif"}
    - {src: "images/Icon_inducks.gif", dest: "/var/www/html/resources/comicwiki/images/Icon_inducks.gif"}
    - {src: "images/Icon_Nummer_9_MM.gif", dest: "/var/www/html/resources/comicwiki/images/Icon_Nummer_9_MM.gif"}
    - {src: "images/Icon_Planet_Pulp.gif", dest: "/var/www/html/resources/comicwiki/images/Icon_Planet_Pulp.gif"}
    - {src: "images/Icon_ddfr.gif", dest: "/var/www/html/resources/comicwiki/images/Icon_ddfr.gif"}
  become: true
