---
- name: Install apache2
  apt: name=apache2 state=present update_cache=yes
  become: true

- name: Install Apache modules
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - modsecurity-crs
    - libapache2-mod-php
  become: true

- name: Install mod_pagespeed
  apt:
    deb: https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_amd64.deb
  become: true

- name: Create sites directories
  file:
    state=directory
    path={{ item }}
    mode=0755
    owner=www-data
    group=www-data
  with_items:
    - /etc/apache2/sites-available
    - /etc/apache2/sites-enabled
  become: true

- name: Make ports listen on IPv4 and IPv6
  template:
    src: ports.conf
    dest: /etc/apache2/ports.conf
    mode: 0644
    owner: www-data
    group: www-data
  become: true

- name: Auxiliary security configuration
  template:
    src: security.conf
    dest: /etc/apache2/conf-available/security.conf
    mode: 0644
    owner: www-data
    group: www-data
  become: true

- name: Copy available sites
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: www-data
    group: www-data
    mode: 0644
  with_items:
    - {src: '000-default.conf.j2', dest: '/etc/apache2/sites-available/000-default.conf'}
    - {src: 'default-ssl.conf.j2', dest: '/etc/apache2/sites-available/default-ssl.conf'}
  become: true

- name: Enable sites
  file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: www-data
    group: www-data
  with_items:
    - {src: '/etc/apache2/sites-available/000-default.conf', dest: '/etc/apache2/sites-enabled/000-default.conf'}
    - {src: '/etc/apache2/sites-available/default-ssl.conf', dest: '/etc/apache2/sites-enabled/default-ssl.conf'}
  become: true

- name: Enable apache module
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - headers
    - rewrite
    - expires
    - ssl
    - pagespeed
    - security2
  become: true
