---
- name: Install apache2
  apt: name=apache2 state=latest update_cache=yes

- name: Install Apache modules
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - modsecurity-crs
    - libapache2-mod-php

- name: Install mod_pagespeed
  apt:
    deb: https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_amd64.deb

- name: Create sites directories
  file:
    state=directory
    path={{ item }}
    mode=0755
    owner=www-data
    group=www-data
  with_items:
    - /etc/apache2/sites-available
    - /etc/apache2/sites-enabled

- name: Copy available sites
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner=www-data
    group=www-data
    mode=0644
  with_items:
    - {src: '000-default.conf.j2', dest: '/etc/apache2/sites-available/000-default.conf'}
    - {src: 'default-ssl.conf.j2', dest: '/etc/apache2/sites-available/000-default.conf'}
