- name: Install apache2
  ansible.builtin.apt:
    name: apache2
    state: present
    update_cache: true
  become: true

- name: Install Apache modules
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  with_items:
    - modsecurity-crs
    - libapache2-mod-php
    - libapache2-mod-apparmor
  become: true

- name: Install mod_pagespeed
  ansible.builtin.apt:
    deb: https://dl-ssl.google.com/dl/linux/direct/mod-pagespeed-stable_current_amd64.deb
  become: true

- name: Create sites directories
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    mode: "0755"
    owner: www-data
    group: www-data
  with_items:
    - /etc/apache2/sites-available
    - /etc/apache2/sites-enabled
  become: true

- name: Enable apache module
  community.general.apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
    - headers
    - rewrite
    - expires
    - ssl
    - pagespeed
  become: true
  notify: Restart apache

- name: Make ports listen on IPv4 and IPv6
  ansible.builtin.template:
    src: ports.conf
    dest: /etc/apache2/ports.conf
    mode: "0644"
    owner: www-data
    group: www-data
  become: true

- name: Auxiliary security configuration
  ansible.builtin.template:
    src: security.conf
    dest: /etc/apache2/conf-available/security.conf
    mode: "0644"
    owner: www-data
    group: www-data
  become: true

- name: Enable security configuration
  ansible.builtin.file:
    state: link
    src: /etc/apache2/conf-available/security.conf
    path: /etc/apache2/conf-enabled/security.conf
    owner: www-data
    group: www-data
  become: true

- name: Copy available sites
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: www-data
    group: www-data
    mode: "0644"
  with_items:
    - {src: '000-default.conf.j2', dest: '/etc/apache2/sites-available/000-default.conf'}
    - {src: 'default-ssl.conf.j2', dest: '/etc/apache2/sites-available/default-ssl.conf'}
  become: true

- name: Enable sites
  ansible.builtin.file:
    state: link
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: www-data
    group: www-data
  with_items:
    - {src: '/etc/apache2/sites-available/000-default.conf', dest: '/etc/apache2/sites-enabled/000-default.conf'}
    - {src: '/etc/apache2/sites-available/default-ssl.conf', dest: '/etc/apache2/sites-enabled/default-ssl.conf'}
  become: true
  notify:
    - Reload apache

- name: Create modsecurity configuration
  ansible.builtin.template:
    src: modsecurity.conf.j2
    dest: /etc/modsecurity/modsecurity.conf
    mode: "0644"
    group: root
    owner: root
  become: true
  notify:
    - Restart apache

- name: Create Apache configuration
  ansible.builtin.template:
    src: apache2.conf.j2
    dest: /etc/apache2/apache2.conf
    mode: "0644"
    group: www-data
    owner: www-data
  become: true
  notify:
    - Restart apache

- name: Copy over logrotate configuration
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/apache2
    mode: "0644"
    group: root
    owner: root
  become: true

- name: Create PHP configuration for Apache
  ansible.builtin.template:
    src: php.ini.j2
    dest: "{{ lookup('ansible.builtin.env', 'PHP_INI_DIR') }}/php.ini"
    mode: "0644"
    group: root
    owner: root
  become: true
  notify:
    - Restart apache
