---
- name: Install apache2
  apt: name=apache2 state=latest update_cache=yes

- name: Install PHP and Apache modules
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - modsecurity-crs
    - libapache2-mod-php
    - php7.2
    - php7.2-mysqli
    - php7.2-mbstring
    - php7.2-json
    - php7.2-common

- name: Create sites directories
  file:
    state=directory
    path={{ item }}
    mode=0755
    owner=www-data
    group=www-data
  with_items:
    - /etc/apache2/sites-available
    - /etc/apache2/sites-enabled

- name: Copy available sites
  template:
    src={{ item.src }}
    dest={{ item.dest }}
    owner=www-data
    group=www-data
    mode=0644
  with_items:
    - {src: '000-default.conf.j2', dest: '/etc/apache2/sites-available/000-default.conf'}
    - {src: 'default-ssl.conf.j2', dest: '/etc/apache2/sites-available/000-default.conf'}
