---
- name: Install postfix packages
  apt: name={{ item }} state=present
  with_items:
    - postfix
    - dovecot-core
    - mailutils
    - procmail
  become: true

# Configuration is based on
# https://linux-audit.com/postfix-hardening-guide-for-security-and-privacy/
# https://help.ubuntu.com/lts/serverguide/postfix.html.en

- name: Create sasl folder
  file:
    state: directory
    path: /etc/postfix/sasl/
    owner: root
    group: root
    mode: 0755
  become: true

- name: Copy default configuration
  template:
    src: sasl_passwd
    dest: /etc/postfix/sasl/sasl_passwd
    mode: 0600
    owner: root
    group: root
  become: true
  notify:
    - postmap sasl_passwd
    - restart postfix

- name: Copy default configuration
  template:
    src: main.cf
    dest: /etc/postfix/main.cf
    mode: 0644
    owner: root
    group: root
  become: true
  notify:
    - restart postfix
