---
- name: Install OpenDKIM packages
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - opendkim
      - opendkim-tools
  become: true

- name: Copy over the default configuration for OpenDKIM
  template:
    src: default.opendkim.j2
    dest: /etc/default/opendkim
    mode: 0644
    owner: root
    group: root
  become: true

- name: Make directory for OpenDKIM keys
  file:
    path: /etc/opendkim/keys/comicwiki.dk
    state: directory
    owner: root
    group: opendkim
    recurse: true
  become: true

- name: Generate keys for OpenDKIM
  command: opendkim-genkey -s mail -d comicwiki.dk
  args:
    chdir: /etc/opendkim/keys/comicwiki.dk
    creates: /etc/opendkim/keys/comicwiki.dk/mail.private
  become: true

- name: Adjust rights for the public key
  file:
    path: /etc/opendkim/keys/comicwiki.dk/mail.txt
    owner: root
    group: opendkim
    mode: 0644
  become: true

- name: Copy over different configuration file for OpenDKIM
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: opendkim
    mode: 0644
  with_items:
    - {src: 'TrustedHosts', dest: '/etc/opendkim/TrustedHosts'}
    - {src: 'KeyTable', dest: '/etc/opendkim/KeyTable'}
    - {src: 'SigningTable', dest: '/etc/opendkim/SigningTable'}
  become: true

- name: Activate the DKIM milter
  blockinfile:
    path: /etc/postfix/main.cf
    # inserted at the end of the file
    block: |
      #
      # Add the DKIM milter
      milter_default_action = accept
      milter_protocol = 2
      smtpd_milters = inet:localhost:12301
      non_smtpd_milters = inet:localhost:12301
  notify:
    - restart postfix
    - restart opendkim
