---
- name: Restart apache
  service:
    name: apache2
    state: restarted
  become: true

- name: Stop apache
  service:
    name: apache2
    state: stopped
  become: true

- name: Reload apache
  service:
    name: apache2
    state: reloaded
  become: true
