# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN apt-get update && apt-get upgrade -y && \
    apt-get install -yu python-is-python3 sudo bash ca-certificates && \
    apt-get clean && \
    rm -rf /var/apt/lists*
