# ---
# dependency:
#   name: galaxy
# driver:
#   name: docker
# lint:
#   name: yamllint
# platforms:
#   - name: ubuntu
#     image: ubuntu:18.04
#     privileged: true
#     pull: true
#     extra_hosts:
#       - "comicwiki.dk:127.0.0.1"
#       - "lvh.me:127.0.0.1"
# provisioner:
#   name: ansible
#   lint:
#     name: ansible-lint
# scenario:
#   name: default
# verifier:
#   name: testinfra
#   lint:
#     name: flake8
---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rhel8
    image: registry.access.redhat.com/ubi8/ubi-init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/usr/sbin/init"
    pre_build_image: true
  - name: ubuntu
    image: ubuntu:22.04
    privileged: true
    pull: true
    extra_hosts:
      - "comicwiki.dk:127.0.0.1"
      - "lvh.me:127.0.0.1"
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    command: "/lib/systemd/systemd"
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
