---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu:22.04
    privileged: true
    extra_hosts:
      - "comicwiki.dk:127.0.0.1"
      - "lvh.me:127.0.0.1"
  - name: ubuntu
    image: ubuntu:24.04
    privileged: true
    extra_hosts:
      - "comicwiki.dk:127.0.0.1"
      - "lvh.me:127.0.0.1"
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
