---
galaxy_info:
  author: Mads Jensen
  description: Role to manage letsencrypt certificates
  namespace: comicwiki
  role_name: letsencrypt

  license: BSD

  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - all

  galaxy_tags: []

dependencies: []
# List your role dependencies here, one per line. Be sure to remove the '[]' above,
# if you add dependencies to this list.
