---
- name: Install python mysql package
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3-pymysql
      - python3-mysqldb
      - python3-pip
      - python3-dev
      - python-pip  # setuptools
      - libmysqlclient-dev
      - python-mysql.connector

- name: Install MySQL packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mysql-server
      - mysql-client
  notify:
    - Restart mysql

- name: Install pymysql
  ansible.builtin.pip:
    name: pymysql

- name: Start MySQL
  ansible.builtin.service:
    name: mysql
    enabled: true
    state: restarted

- name: Generate new root password
  ansible.builtin.command: |
    openssl rand -hex 7
  args:
    creates: /root/.my.cnf
  register: mysql_new_root_pass

- name: Update root password
  mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_new_root_pass.stdout }}"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  when: mysql_new_root_pass.changed
  tags:
    - skip_ansible_lint

- name: Create my.cnf
  ansible.builtin.template:
    src: templates/mysql/my.cnf
    desc: /root/.my.cnf
  when: mysql_new_root_pass.changed
  tags:
    - skip_ansible_lint

- name: Create the database
  community.mysql.mysql_db:
    name: comicwiki
    state: present

- name: Removes anonymous user account for localhost
  community.mysql.mysql_user:
    name: ''
    host_all: true
    state: absent

# TODO set a password for the root user in mysql to get rid of the no-password
# warning from mysqltuner

- name: Make database user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
    user: "root"
    login_user: "root"
    login_password: 'joke'
  notify:
    - Restart mysql

# not used, but nice to have for SystemD reference checks
- name: Make MySQL restart check
  ansible.builtin.template:
    src: mysqlcheck.sh
    dest: /usr/local/bin/mysqlcheck.sh
    mode: "0755"
    owner: root
    group: root

- name: Create self-signed certificates
  ansible.builtin.command: |
    mysql_rsa_ssl_setup --uid=mysql
  args:
    creates: /var/lib/mysql/server-cert.pem
