---
- name: Install python mysql package
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3-pymysql
      - python3-mysqldb
      - python3-pip
      - python3-dev
      - libmysqlclient-dev
      - python3-mysql.connector

- name: Install MySQL packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mysql-server
      - mysql-client
  notify:
    - Restart mysql

- name: Start MySQL
  ansible.builtin.service:
    name: mysql
    enabled: true
    state: restarted
  become: true

- name: Generate new root password
  ansible.builtin.command: |
    openssl rand -hex 7
  args:
    creates: /root/.my.cnf
  register: mysql_new_root_pass

- name: Update root password
  community.mysql.mysql_user:
    name: "root"
    host: "{{ item }}"
    password: "{{ mysql_new_root_pass.stdout }}"
    login_user: "root"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    login_password: ""
    login_host: "localhost"
  with_items:
    - "{{ ansible_hostname }}"
    - "127.0.0.1"
    - "::1"
    - "localhost"
  when: mysql_new_root_pass.changed
  tags:
    - skip_ansible_lint
  become: true

- name: Create my.cnf
  ansible.builtin.template:
    src: "my.cnf.j2"
    dest: "/root/.my.cnf"
    mode: "0600"
    owner: "root"
    group: "root"
  when: mysql_new_root_pass.changed
  tags:
    - skip_ansible_lint
  become: true

- name: Set mysql user privileges
  community.mysql.mysql_user:
    name: root
    priv: "comicwiki.*:ALL"
    state: present
  become: true

- name: Create the database
  community.mysql.mysql_db:
    name: comicwiki
    state: present
  become: true

- name: Make database user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
    user: "root"
    login_user: "root"
    login_password: "{{ mysql_new_root_pass.stdout }}"
  notify:
    - Restart mysql

# not used, but nice to have for SystemD reference checks
- name: Make MySQL restart check
  ansible.builtin.template:
    src: mysqlcheck.sh
    dest: /usr/local/bin/mysqlcheck.sh
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Create self-signed certificates
  ansible.builtin.command:
    cmd: mysql_rsa_ssl_setup --uid=mysql
  args:
    creates: /var/lib/mysql/server-cert.pem
