---
- name: Install python mysql package
  apt: name={{ item }} state=present
  with_items:
    - python3-pymysql
    - python3-mysqldb
    - python3-dev
    - libmysqlclient-dev
    - python-mysql.connector
  become: true

- name: Install MySQL packages
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
  become: true

- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
  become: true

- name: Make database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
  become: true
  notify:
    - Restart mysql

- name: Make MySQL restart check
  template:
    src: mysqlcheck.sh
    dest: /usr/local/bin/mysqlcheck.sh
    mode: 0755
    owner: root
    group: root
  become: true

- name: Restart MySQL if needed
  cron:
    minute: "*/5"
    job: "/usr/local/bin/mysqlcheck.sh"
  become: true
