---
- name: Install python mysql package
  apt: name={{ item }} state=present
  with_items:
    - python3-pymysql
    - python3-mysqldb
    - python3-dev
    - libmysqlclient-dev
    - python-mysql.connector
  become: true

- name: Install MySQL packages
  apt: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql-client
  notify:
    - Start mysql
  become: true

- name: Removes anonymous user account for localhost
  mysql_user:
    name: ''
    host: localhost
    state: absent
  become: true

- name: Make database user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
  become: true
  become_user: root
  notify:
    - Restart mysql

# - name: Import file.sql similar to mysql -u <username> -p <password> < hostname.sql
#   mysql_db:
#     password: "{{ db_password }}"
#     user: "{{ db_user }}"
#     state: import
#     name: all
#     target: /tmp/comicwiki.dk.sql
#   when: import is True
