---
- name: Install python mysql package
  ansible.builtin.apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3-pymysql
      - python3-mysqldb
      - python3-pip
      - python3-dev
      - libmysqlclient-dev
      - python3-mysql.connector

- name: Install MySQL packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - mysql-server
      - mysql-client
  notify:
    - Restart mysql

- name: Start MySQL
  ansible.builtin.service:
    name: mysql
    enabled: true
    state: started

- name: Save root password in .my.cnf
  ansible.builtin.template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: "0600"

- name: Update MySQL root user password
  community.mysql.mysql_user:
    name: root
    login_unix_socket: /var/run/mysqld/mysqld.sock
    host: "localhost"
    password: "{{ mysql_root_password }}"
    priv: "*.*:ALL,GRANT"
    check_implicit_admin: true
    column_case_sensitive: true

- name: Create the database
  community.mysql.mysql_db:
    name: comicwiki
    state: present

- name: Make database user
  community.mysql.mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: 'comicwiki.*:ALL'
    state: present
    column_case_sensitive: true

# not used, but nice to have for SystemD reference checks
- name: Make MySQL restart check
  ansible.builtin.template:
    src: mysqlcheck.sh
    dest: /usr/local/bin/mysqlcheck.sh
    mode: "0755"
    owner: root
    group: root
  become: true

- name: Create self-signed certificates
  ansible.builtin.command:
    cmd: mysql_rsa_ssl_setup --uid=mysql
  args:
    creates: /var/lib/mysql/server-cert.pem
