---
- name: update composer
  composer:
    command: update
    working_dir: /var/www/html
  become: true

- name: reset pagespeed
  file:
    path: /var/cache/mod_pagespeed/cache.flush
    state: touch
  become: true

- name: reset chameleon
  file:
    path: /var/www/html/LocalSettings.php
    state: touch
  become: true
