---
dependency:
  name: galaxy
driver:
  name: docker
  options:
    managed: False
    login_cmd_template: 'docker exec -ti {instance} bash'
    ansible_connection_options:
      ansible_connection: docker
platforms:
  - name: instance
    image: ubuntu:22.04
    privileged: true
  - name: instance
    image: ubuntu:24.04
    privileged: true
provisioner:
  name: ansible
  config_options:
    defaults:
      vault_password_file: ~/vault.pw
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
lint: |
  set -e

  ansible-lint
  flake8
