---
- name: Prepare
  hosts: all
  tasks:
    - name: Create a container
      community.docker.docker_container:
        name: "{{ item.name }}"
        image: "{{ item.image }}"
        state: started
        command: sleep 1d
        log_driver: json-file
      register: result
      loop: "{{ molecule_yml.platforms }}"

    - name: Update apt cache
      ansible.builtin.apt:
        cache_valid_time: 3600
        update_cache: true

    - name: Install Python3
      ansible.builtin.apt:
        name: python
        install_recommends: true
        state: latest
      
