---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ubuntu:22.04
    privileged: true
  - name: instance
    image: ubuntu:24.04
    privileged: true
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../
  config_options:
    defaults:
      vault_password_file: ~/vault.pw
  lint:
    name: ansible-lint
  options:
    vvv: true
scenario:
  name: default
verifier:
  name: testinfra
