---
- hosts: server
  gather_facts: true
  roles:
    - {role: base, bcome: true}
    - {role: letsencrypt, become: true}
    - {role: apache}
    - {role: mysql, become: true}
    - {role: mediawiki}
    - {role: security, become: true}
