---
- hosts: server
  gather_facts: false
  vars:
    run_in_container: false
  roles:
    - base
    - {role: letsencrypt, become: true}
    - apache
    - {role: mysql, become: true}
    - mediawiki
    - {role: security, become: true}
