---
- name: Install fail2ban and iptables
  apt: name={{ item }} state=present
  with_items:
    - iptables
    - iptables-persistent
    - fail2ban
    - unattended-upgrades
  become: true

- name: iptables accept related
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6
  become: true

- name: Configure iptables ports
  iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item.port }}"
    ctstate: NEW
    jump: ACCEPT
    ip_version: "{{ item.version }}"
  with_items:
    - {port: 22, version: "ipv4"}
    - {port: 22, version: "ipv6"}
    - {port: 80, version: "ipv4"}
    - {port: 80, version: "ipv6"}
    - {port: 443, version: "ipv4"}
    - {port: 443, version: "ipv6"}
  become: true
  become_user: root
  notify:
    - netfilter restart

- name: Firewall rule - allow all loopback traffic
  iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  become: true
  become_user: root

- name: Disable icmp ping ipv4
  iptables:
    chain: INPUT
    protocol: icmp
    icmp_type: "echo-request"
    jump: DROP
  become: true

- name: Disable icmp ping ipv6
  iptables:
    chain: INPUT
    protocol: ipv6-icmp
    icmp_type: "echo-request"
    jump: DROP
    ip_version: ipv6
  become: true

- name: Firewall rule - drop any traffic without rule
  iptables:
    chain: INPUT
    jump: DROP
  become: true
  become_user: root

- name: SSH server settings
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0644
    owner: root
    group: root
  become: true
  become_user: root
  notify:
    - restart ssh

- name: Override some basic fail2ban configurations
  template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  become: true

- name: Activitate unattended upgrades
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  become: true
  become_user: root
  with_items:
    - {src: "20auto-upgrades.j2", dest: "/etc/apt/apt.conf.d/20auto-upgrades"}
    - {src: "50unattended-upgrades.j2", dest: "/etc/apt/apt.conf.d/50unattended-upgrades"}
  notify:
    - unattended-upgrades restart

- name: Tweak kernel parameters for security
  sysctl:
    name: net.ipv4.ip_forward
    value: 0
    sysctl_file: /etc/sysctl.conf
    reload: true
  become: true
