---
- name: Install fail2ban and iptables
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - iptables
      - iptables-persistent
      - fail2ban
      - unattended-upgrades
      - apparmor

- name: Remove unneeded tools
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
      - telnet

- name: Configure iptables accept related
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
    ip_version: "{{ item }}"
  with_items:
    - ipv4
    - ipv6
  notify:
    - Save iptables

- name: Configure iptables ports
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: "{{ item.port }}"
    ctstate: NEW
    jump: ACCEPT
    ip_version: "{{ item.version }}"
  with_items:
    - {port: 22, version: "ipv4"}
    - {port: 22, version: "ipv6"}
    - {port: 80, version: "ipv4"}
    - {port: 80, version: "ipv6"}
    - {port: 443, version: "ipv4"}
    - {port: 443, version: "ipv6"}
  notify:
    - Save iptables

- name: Firewall rule - allow all loopback traffic
  ansible.builtin.iptables:
    action: append
    chain: INPUT
    in_interface: lo
    jump: ACCEPT
  notify:
    - Save iptables

- name: Disable icmp ping ipv4
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    icmp_type: "echo-request"
    jump: DROP
  notify:
    - Save iptables

- name: Disable icmp ping ipv6
  ansible.builtin.iptables:
    chain: INPUT
    protocol: ipv6-icmp
    icmp_type: "echo-request"
    jump: DROP
    ip_version: ipv6
  notify:
    - Save iptables

- name: Firewall rule - drop any traffic without rule
  ansible.builtin.iptables:
    chain: INPUT
    jump: DROP
  become: true
  become_user: root
  notify:
    - Save iptables

- name: SSH server settings
  ansible.builtin.template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart ssh

- name: Override some basic fail2ban configurations
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"

- name: Activitate unattended upgrades
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - {src: "20auto-upgrades.j2", dest: "/etc/apt/apt.conf.d/20auto-upgrades"}
    - {src: "50unattended-upgrades.j2", dest: "/etc/apt/apt.conf.d/50unattended-upgrades"}
  notify:
    - Restart unattended-upgrades

# most of them were added from
# - https://www.cyberciti.biz/faq/linux-kernel-etcsysctl-conf-security-hardening/
# - https://blog.confirm.ch/sysctl-tuning-linux/
- name: Tweak kernel parameters for security
  ansible.posix.sysctl:
    name: "{{ item.parameter }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.conf
    reload: true
  with_items:
    - {parameter: "net.ipv4.ip_forward", value: "0"}
    - {parameter: "net.ipv4.icmp_echo_ignore_broadcasts", value: "1"}
    - {parameter: "net.ipv4.conf.all.rp_filter", value: "1"}
    - {parameter: "net.ipv4.conf.default.rp_filter", value: "1"}
    - {parameter: "net.ipv4.conf.lo.rp_filter", value: "1"}
    - {parameter: "net.ipv4.conf.eth0.rp_filter", value: "1"}
    - {parameter: "net.ipv6.conf.all.forwarding", value: "1"}
    - {parameter: "net.ipv4.conf.all.log_martians", value: "1"}
    - {parameter: "net.ipv4.conf.default.accept_source_route", value: "0"}
    - {parameter: "net.ipv4.conf.default.accept_redirects", value: "0"}
    - {parameter: "net.ipv4.conf.default.secure_redirects", value: "0"}
    - {parameter: "net.ipv4.conf.all.send_redirects", value: "0"}
    - {parameter: "net.ipv4.conf.default.send_redirects", value: "0"}
    - {parameter: "net.ipv4.icmp_echo_ignore_broadcasts", value: "1"}
    - {parameter: "net.ipv6.conf.all.accept_ra", value: "0"}
    - {parameter: "net.ipv6.conf.default.accept_ra", value: "0"}
    - {parameter: "net.ipv6.conf.default.router_solicitations", value: "0"}
    - {parameter: "net.ipv6.conf.all.router_solicitations", value: "0"}
    - {parameter: "net.ipv6.conf.default.max_addresses", value: "1"}

- name: Create securetty
  ansible.builtin.template:
    src: securetty.j2
    dest: /etc/securetty
    owner: root
    group: root
    mode: "0400"
