---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  ansible-lint
  yamllint
platforms:
  - name: instance
    image: "ubuntu:22.04"
    pull: true
    hostname: comicwiki.dk
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - name: instance
    image: "ubuntu:24.04"
    pull: true
    hostname: comicwiki.dk
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
