---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "ubuntu:22.04"
    hostname: comicwiki.dk
    privileged: true
  - name: instance
    image: "ubuntu:24.04"
    hostname: comicwiki.dk
    privileged: true
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
